---
driver:
  name: docker
  use_sudo: false

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.3

provisioner:
  name: salt_solo
  formula: maxscale
  pillars:
    top.sls:
      base:
        '*':

  state_top:
    base:
      '*':
        - maxscale
suites:
  - name: default
    run_list:
    attributes:
