<%
require 'yaml'

formula = YAML.load_file('FORMULA')
formula_name = formula['name']
%>
---
driver:
  name: docker
  use_sudo: false
  privileged: true
  
platforms:
  - name: ubuntu-14.04
    image: ubuntu-upstart:14.04
    driver_config:
      run_command: /sbin/init
  - name: ubuntu-16.04
    driver_config:
      run_command: /bin/systemd
  - name: centos-7
    driver_config:
      run_command: /usr/lib/systemd/systemd

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  salt_pillar_root: pillar.example
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  formula: <%= formula_name %>
  pillars-from-files:
    maxscale.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - maxscale
  state_top:
    base:
      '*':
        - <%= formula_name %>
suites:
  - name: default
