language: ruby
sudo: true

services:
  - docker

addons:
  apt:
    packages:
      - curl
      - git
      - apt-transport-https

before_script:
  - sudo iptables -L DOCKER || sudo iptables -N DOCKER

script:
  - bundle exec kitchen verify
