language: ruby

sudo: true

services:
  - docker

addons:
  apt:
    packages:
      - curl
      - git
      - python-pip
      - apt-transport-https
      - kitchen

rvm:
  - ruby

before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

before_install:
  - sudo gem install test-kitchen kitchen-salt kitchen-docker

script:
  - kitchen verify