language: ruby

sudo: true

services:
  - docker

addons:
  apt:
    packages:
      - curl
      - git
      - apt-transport-https

before_install:
  - curl -s https://packagecloud.io/install/repositories/chef/stable/script.deb.sh | sudo bash
install:
  - sudo apt-get install chefdk
  - /opt/chefdk/bin/chef gem install kitchen-docker kitchen-salt

script:
  - /opt/chefdk/bin/chef kitchen verify