language: ruby

sudo: true

services:
  - docker

addons:
  apt:
    packages:
      - curl
      - git
      - apt-transport-https

before_install:
  - curl -O https://packages.chef.io/files/stable/chefdk/2.3.1/ubuntu/14.04/chefdk_2.3.1-1_amd64.deb
  - sudo dpkg -i chefdk_2.3.1-1_amd64.deb
install:
  - /opt/chefdk/bin/chef gem install test-kitchen kitchen-docker kitchen-salt

before_script:
  - sudo iptables -L DOCKER || sudo iptables -N DOCKER


script:
  - /opt/chefdk/bin/chef exec kitchen verify